# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='School Name', max_length=100)),
                ('teacher_name', models.CharField(help_text='Teacher Name', max_length=100)),
                ('grade', models.IntegerField(help_text='Teacher grade number')),
                ('datetime', models.DateTimeField(help_text='Date time')),
                ('comments', models.CharField(help_text='Comments (optional)', max_length=1000)),
            ],
        ),
    ]
