# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
