# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='district',
            field=models.CharField(default='dist', help_text='District Name', max_length=100),
            preserve_default=False,
        ),
    ]
